### ISSUE TITLE
PHP7, PSR and Composer

### ISSUE THREAD

**Issue by ghost** [Qybercom/quark#30]
Hi @chief93,

What is your view on applying common PHP development practices in Quark?

These might be:
- Using some composer dependencies (ex. dotenv), or at least making quark a composer package itself
- Using PHP7 features
- Following PSR recommendations

Just interested. :package:

**Comment by chief93** [comment]
@tjomamokrenko first of all, thanks for these questions, because I knew that someone will ask them one time)

1. I don't use Composer for that project, because I intended this framework for all types of deployment, inclusive virtual hostings on various types of OS. That mean that Composer isn't available there. For other installations there are no difficulties with simple `$ git clone https://github.com/Qybercom/quark.git` or more simple - pasting the `.zip` archive on target installation.
2. Quark is fully compatible with PHP7 (maybe some issues with old `MongoDB` driver), but in most OS are still `5.4.*` and greater official PHP versions (for example, in `apt-get` official PHP version is still `5.6.*`), and this is minimal supported version of PHP, so we need to ensure that framework and projects based on it, will work in different environments. There are some installations with correct working of Quark on PHP5.3 (by the way on a virtual hosting), but this is not fully supported.
3. I prefer `PSR-0` for loading dependencies, because it is most performant way to load them. Tests with other frameworks based on `PSR-4` and other is [here](http://pastebin.com/mtfRR3Kv).

Quark is designed for `pass-the-failure` work, that means that it will aim to handle expected behavior. Some already working projects, based on it, are proving that idea.

I thought about using PHP7 simple types hinting, but now it wiil be not a good idea.

**Comment by tjomamokrenko** [comment]
@chief93 Thank you for your answer

I've got your position on everything except Composer. It's not really about deployment, it's more about _dependency management_. Which means we can **reuse other depeveloper's code**, when using Composer. Also, you must be mistaken about platforms, since Composer runs everywhere where PHP does (obviously, because it's written in PHP). So why wouldn't you reuse other developer's code?

**Comment by chief93** [comment]
@tjomamokrenko please, run Composer on any virtual hosting without SSH terminal access)

About dependencies - if you look at commit history, you can find my try of  `facebook-php-sdk` git-submodule integration, and it didn't matched requirements, setted for `SocialNetwork` component. So, I figured out that It's need to be self designed coding practices for Quark. All `Extensions` and `ViewResources` absolutelly confirm that decision. And one more big argument for monolite architecture - code base will be understood by any contributor or user, so will be more simple to roll patches.

P.S. I am not agree with some PSR statements, or PHP community code style, people can make architectural mistakes, even if they are PHP core contributors.

**Comment by tjomamokrenko** [comment]
> `run Composer on any virtual hosting without SSH terminal access`
You are free to run `composer install` on one host and then upload the results to another. You may have a special sort of distributions which already have all dependencies installed. The question here is not in execution or deploement, it's in code reuse.

**Comment by chief93** [comment]
@tjomamokrenko this is not an option, because we will have same situation like direct pasting of `.zip` archive) and about dependencies - I already answered WHY there is no need.

**Comment by tjomamokrenko** [comment]
Well, it is an option because it can be done one of these two ways, and
it's what an option is all about.
And also you just said that code reuse is useless – it just can't be, there
are many libraries that took weeks to implement and this time must be saved
for the future projects. And you know, business does not care about code
style (I find current CS standarts pretty cool) or any other obstacles of
such kind on the way to business value. What it cares about is a **fast**
and **sustainable** way to test business hypothesises or to build a
product.
On Apr 19, 2016 4:41 PM, "Alex Furnica" <notifications@github.com> wrote:

@tjomamokrenko <https://github.com/tjomamokrenko> first of all, thanks for
these questions, because I knew that someone will ask them one time)

   1. I don't use Composer for that project, because I intended this
   framework for all types of deployment, inclusive virtual hostings on
   various types of OS. That mean that Composer isn't available there. For
   other installations there are no difficulties with simple $ git clone
   https://github.com/Qybercom/quark.git or more simple - pasting the .zip
   archive on target installation.
   2. Quark is fully compatible with PHP7 (maybe some issues with old
   MongoDB driver), but in most OS are still 5.4.* and greater official PHP
   versions (for example, in apt-get official PHP version is still 5.6.*),
   and this is minimal supported version of PHP, so we need to ensure that
   framework and projects based on it, will work in different environments.
   There are some installations with correct working of Quark on PHP5.3 (by
   the way on a virtual hosting), but this is not fully supported.
   3. I prefer PSR-0 for loading dependencies, because it is most
   performant way to load them. Tests with other frameworks based on PSR-4
   and other is here <http://pastebin.com/mtfRR3Kv>.

Quark is designed for pass-the-failure work, that means that it will aim to
handle expected behavior. Some already working projects, based on it, are
proving that idea.

I thought about using PHP7 simple types hinting, but now it wiil be not a
good idea.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Qybercom/quark/issues/30#issuecomment-211927130>

**Comment by chief93** [comment]
@tjomamokrenko I thought I clearly explained WHY I don't use third-party libraries it this project =\ Yes, their implementation can took weeks\month\years\epochs, but they don't match given requirements. And, I say it again: framework is not an ordinary project, which need to be developed "as is". All it's code base MUST be solid and homogeneous, it's MUST NOT be a collection of isolated "best practices", like  Symfony. Please, don't refer to "business cases", because such framework as .NET or Qt perfect resolves this "issue" with great results for business. This is a part of Quark philosophy, which was born before first line of Quark code.
